---
:concurrency: 5
production:
  :concurrency: 5
:queues:
  - critical
  - default
  - checks
  - migrations
  - reindex
  - searchkick
  - low
  - crawlers
:process_limits:
  critical: 4
  default: 3
  crawlers: 3
  checks: 3
  migrations: 2
  low: 2
  searchkick: 1
